spring:
  cloud:
    config:
      uri: http://localhost:8888
      failFast: false


eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enable-self-preservation: false
