server:
  port: 8888
spring.application.name: config-server

spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:/app/config

eureka:
  client:
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://server-discovery:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 20
    leaseExpirationDurationInSeconds: 30
  metadataMap:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

