server:
  port: 8084

# Logback 에서 yml 찾지 못함.
spring.application.name: mail-service
logging.level:
  org.springframework.*: debug
#spring.profiles.active: mail
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: test
    virtual-host: /test
  cloud:
    stream:
      bindings:
#         Input
        do-cert-mail:
          group: group.join
          destination: queue.notify.mail
      rabbit:
        bindings:
          from-signup:
            consumer:
              requeueRejected: false
              autoBindDlq: true
              republishToDlq : true

mail:
  enable: false
  host: smtp.gmail.com
  port: 587
  protocol: smtp
  default-encoding: UTF-8
  email: sendermail888@gmail.com
  password: mailsender!@#
  debug: true
  smtp:
    start-tls-enable: true
    auth: true