mail:
  enable: true
  host: smtp.gmail.com
  port: 587
  protocol: smtp
  default-encoding: UTF-8
  email: sendermail888@gmail.com
  password: mailsender!@#
  debug: true
  smtp:
    start-tls-enable: true
    auth: true

shooter:
  origin:
    enable: true
    host: localhost
    port: 4200
  repoter:
#  Second
    frequency: 10