server:
  port: 8082

# Logback 에서 yml 찾지 못함.
spring.application.name: user-service

logging:
  config: external-config/logback-spring.xml

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: test
    virtual-host: /test

    binding:
      mail:
        queue: mail.queue
        exchange: mail.direct
        rountingKey: mail.queue
      oauth:
        queue: oauth.queue
        exchange: oauth.direct
        rountingKey: oauth.queue


spring.profiles.active: mysql
---
spring:
  profiles: h2
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/user_service;Mode=MySQL;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS \"public\";
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: mysql
  datasource:
      url: jdbc:mysql://localhost:3306/user_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: test
      password: test
      driver-class-name: com.mysql.jdbc.Driver
      test-on-borrow: true
      test-while-idle: true
      validation-query: select 1
      max-active: 10
      max-idle: 5
      min-idle: 1
      initial-size: 5
      time-between-eviction-runs-millis: 5000
      min-evictable-idle-time-millis: 60000
  jpa:
      show-sql: true
#      Flyway DB 를 사용하여 데이터 초기화를 위하여 주석
#      database: mysql
#      hibernate.ddl-auto: create-drop