server:
  port: 9000

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8081/user/{userName}
      preferTokenInfo: false

proxy:
  auth:
    routes:
      uaa-service: uaa-service