server:
  port: 9000
# Define security
spring.application.name: gateway-service
security:
  basic:
    enabled: false
#  user:
#    password: password
#  ignored: /css/**,/js/**,/favicon.ico,/webjars/**