server:
  port: 9000
  aop:
    proxyTargetClass: true
# Logback 에서 yml 찾지 못함.
spring.application.name: gateway-server
logging:
  config: external-config/logback-spring.xml

security:
  oauth2:
    client:
      accessTokenUri: http://localhost:9000/oauth/token
      userAuthorizationUri: /oauth/authorize