# Define the port where the UAA server would be running
server:
  port: 9999
  # Use different context-path to avoid session cookie overlapping
  context-path: /uaa
# Logback 에서 yml 찾지 못함.
spring:
  application:
    name: uaa-service
