# Define the port where the UAA server would be running
server:
  port: 9999
  # Use different context-path to avoid session cookie overlapping
  context-path: /uaa
  use-forward-headers: false
# Logback 에서 yml 찾지 못함.
spring.application.name: oauth2-service


logging:
  config: external-config/logback-spring.xml

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/oauth_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: test
      password: test
      driver-class-name: com.mysql.jdbc.Driver
      test-on-borrow: true
      test-while-idle: true
      validation-query: select 1
      max-active: 10
      max-idle: 5
      min-idle: 1
      initial-size: 5
      time-between-eviction-runs-millis: 5000
      min-evictable-idle-time-millis: 60000
  jpa:
      show-sql: true
  #      Flyway DB 를 사용하여 데이터 초기화를 위하여 주석
  #      database: mysql
  #      hibernate.ddl-auto: create-drop
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: test
    virtual-host: /test
  cloud:
      stream:
        bindings:
#          join-output:
#            destination: oauth-input
          from-signup:
            consumer:
              maxAttempts: 1
            group: group.signup
            destination: queue.signup
        rabbit:
          bindings:
            from-signup:
              consumer:
                requeueRejected: false
                autoBindDlq: true
                republishToDlq : true
                transacted: true